name: npm test

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --no-lockfile
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
